load("@rules_python//python:defs.bzl", "py_binary")
load("@pip_deps//:requirements.bzl", "requirement")

py_library(
    name = "lib",
    srcs = [
        "compare_files.py"
    ],
    visibility = ["//visibility:public"],
)
